---
- name: Uninstall Apache Server
  hosts: webservers
  vars_files:
    - vars.yml
  become: true
  tasks:
    - name: Uninstall Apache
      apt:
        name: apache2
        state: absent

    - name: Remove all Apache configuration files
      file:
        path: /etc/apache2
        state: absent
